db:
  name: &dbname metastore-postgresql-cluster
  spec:
    teamId: "metastore"
    volume:
      size: 1Gi
    numberOfInstances: 1
    users:
      admin:
      - superuser
      - createdb
      hive:
      - createdb
      - superuser
    databases:
      hivemetastore: hive

image:
  repository: apache/hive
  tag: 4.0.0-alpha-2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9083

replicaCount: 1

hiveSiteXml: |
  <configuration>
    <property>
      <name>javax.jdo.option.ConnectionURL</name>
      <value>jdbc:postgresql://metastore-postgresql-cluster:5432/hivemetastore?createDatabaseIfNotExist=true</value>
      <description>JDBC connect string for a JDBC metastore</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
        <description>Driver class name for a JDBC metastore</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>${env:POSTGRES_USER}</value>
        <description>Username to use against metastore database</description>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>${env:POSTGRES_PASSWORD}</value>
        <description>Password to use against metastore database</description>
    </property>
    <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>true</value>
    </property>
    <property>
        <name>datanucleus.fixedDatastore</name>
        <value>true</value>
    </property>
    <property>
        <name>datanucleus.autoCreateTables</name>
        <value>True</value>
    </property>
  </configuration>

env:
  dbtype: postgres
  dbhost: *dbname