image:
  repository: ghcr.io/bitsondatadev/hive-metastore
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9083

replicaCount: 1

hiveSiteXml: |
  <configuration>
  </configuration>